services:
  moveit2:
    image: moveit2:humble
    build:
      context: .
      dockerfile: docker/Dockerfile.moveit2
      args:
        BASE_IMAGE: osrf/ros:humble-desktop-full
        ROS_DISTRO: humble
        USERNAME: ${USERNAME:-macs}
        UID: ${UID:-1000}
        GID: ${UID:-1000}
        VIDEO_GID: 44
        DIALOUT_GID: 20
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      # Remove all NVIDIA variables since you have Intel GPU
      - XDG_RUNTIME_DIR=/tmp/runtime-${USERNAME:-macs}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./shared_ws:/workspaces/shared_ws:rw
      - /dev/dri:/dev/dri:rw  # Intel GPU device access
      - /dev:/dev
      - /tmp/runtime-${USERNAME:-macs}:/tmp/runtime-${USERNAME:-macs}:rw
    device_cgroup_rules:
      - 'c *:* rmw'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    devices:
      - /dev/dri:/dev/dri  # Direct Intel GPU access
    working_dir: /workspaces/shared_ws
    user: ${UID:-1000}:${UID:-1000}
    command: ["/bin/bash"]